version: 2
jobs:
    build:
        docker:
            - image: circleci/node:11
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests
                command: npm test
            - deploy:
                name: digital-ocean
                command: ssh -o "StrictHostKeyChecking no" user@hostname "cd ~/profile-store; git pull; npm install; forever start app.js"
